"""Define test data files.

**DO NOT PUT PRIVATE AGENTE DATA HERE!!!**
Use the generic agents XXXC, XXXG, XXXD or XXXT for agent (private) test files.

Make sure that the path casing (UPPERCASE, lowerase, etc) is as the local file system.
"""
import pathlib

import pytest

FIXTURE_DIR = pathlib.Path(__file__).parent.resolve() / "RUTA"

TESTFILES = pytest.mark.datafiles(
    FIXTURE_DIR,
    keep_top_dir=True,
)

ALL_FILES = {
    "adem": {
        "path": "/RUTA/PUBLICA/DEL/FTP/2023-10/adem1001.Tx2",
        "kind": "adem",
        "visibility": "public",
        "year": 2023,
        "month": 10,
        "day": 1,
        "extension": ".tx2",
        "version": "001",
        "agent": None,
    },
    "aenc": {
        "path": "/RUTA/PRIVADA/XXXC/DEL/FTP/2023-10/aenc1001.Tx2",
        "kind": "aenc",
        "visibility": "agent",
        "year": 2023,
        "month": 10,
        "day": 1,
        "extension": ".tx2",
        "version": "001",
        "agent": "xxxc",
    },
    "balcttos": {
        "path": "/RUTA/PRIVADA/XXXC/DEL/FTP/2023-10/BalCttos1001.tx2",
        "kind": "balcttos",
        "visibility": "agent",
        "year": 2023,
        "month": 10,
        "day": 1,
        "extension": ".tx2",
        "version": "001",
        "agent": "xxxc",
    },
    "pep": {
        "path": "/RUTA/PUBLICA/DEL/FTP/2023-10/pep1001.tx1",
        "kind": "pep",
        "visibility": "public",
        "year": 2023,
        "month": 10,
        "day": 1,
        "extension": ".tx1",
        "version": "000",
        "agent": None,
    },
    "PME": {
        "path": "/RUTA/PUBLICA/DEL/FTP/2023-10/PME14001.txa",
        "kind": "PME",
        "visibility": "public",
        "year": 2023,
        "month": 10,
        "day": None,
        "extension": ".txa",
        "version": "-001",
        "agent": None,
    },
    "trsd": {
        "path": "/RUTA/PUBLICA/DEL/FTP/2023-10/trsd1001.tx2",
        "kind": "trsd",
        "visibility": "public",
        "year": 2023,
        "month": 10,
        "day": 1,
        "extension": ".tx2",
        "version": "001",
        "agent": None,
    },
    "tfroc": {
        "path": "/RUTA/PRIVADA/XXXC/DEL/FTP/2023-10/tfroc1001.TxF",
        "kind": "tfroc",
        "visibility": "agent",
        "year": 2023,
        "month": 10,
        "day": 1,
        "extension": ".txf",
        "version": "003",
        "agent": "xxxc",
    },
    "tgrl": {
        "path": "/RUTA/PUBLICA/DEL/FTP/2023-10/tgrl1001.tx2",
        "kind": "tgrl",
        "visibility": "public",
        "year": 2023,
        "month": 10,
        "day": 1,
        "extension": ".tx2",
        "version": "001",
        "agent": None,
    },
    "tserv": {
        "path": "/RUTA/PUBLICA/DEL/FTP/2023-10/tserv10.txf",
        "kind": "tserv",
        "visibility": "public",
        "year": 2023,
        "month": 10,
        "day": None,
        "extension": ".txf",
        "version": "003",
        "agent": None,
    },
    "trsm": {
        "path": "/RUTA/PUBLICA/DEL/FTP/2023-10/trsm10.txf",
        "kind": "trsm",
        "visibility": "public",
        "year": 2023,
        "month": 10,
        "day": None,
        "extension": ".txf",
        "version": "003",
        "agent": None,
    },
    "sntie": {
        "path": "/RUTA/PUBLICA/DEL/FTP/2023-10/sntie10.txf",
        "kind": "sntie",
        "visibility": "public",
        "year": 2023,
        "month": 10,
        "day": None,
        "extension": ".txf",
        "version": "003",
        "agent": None,
    },
    "afac": {
        "path": "/RUTA/PUBLICA/DEL/FTP/2023-10/afac10.txf",
        "kind": "afac",
        "visibility": "public",
        "year": 2023,
        "month": 10,
        "day": None,
        "extension": ".txf",
        "version": "003",
        "agent": None,
    },
    "dspcttos": {
        "path": "/RUTA/PRIVADA/XXXC/DEL/FTP/2023-10/dspcttos1001.TxF",
        "kind": "dspcttos",
        "visibility": "agent",
        "year": 2023,
        "month": 10,
        "day": 1,
        "extension": ".txf",
        "version": "003",
        "agent": "xxxc",
    },
    "PTB": {
        "path": "/RUTA/PUBLICA/DEL/FTP/2025-04/PTB0401.txf",
        "kind": "PTB",
        "visibility": "public",
        "year": 2025,
        "month": 4,
        "day": 1,
        "extension": ".txf",
        "version": "003",
        "agent": None,
    },
}
