name: Test
run-name: ${{ github.actor }} is testing

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  test:
    name: Test code
    runs-on: ubuntu-latest
    env:
      ASIC_CONFIG_PATH: tests/TEST_ASIC_FILE_CONFIG.jsonl
      
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        # Run in all these versions of Python
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set up uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Test with pytest
        run: uv run pytest tests

  mypy:
    name: Type check code
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # Run in all these versions of Python
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Set up uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh
      - name: Type check code
        run: uv run mypy src
      - name: Type check tests
        run: uv run mypy tests
